#!/usr/bin/env python3
"""Render worker-owned hard destination denies for the pinned CubeVS patch.

This does not install anything or attest enforcement. Run the BPF and live
isolation tests before enabling domain egress in sandboxd.
"""
import argparse
import ipaddress
from pathlib import Path

MANDATORY = ["0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8",
             "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16",
             "198.18.0.0/15", "224.0.0.0/4", "240.0.0.0/4"]


def network(value):
    result = ipaddress.ip_network(value, strict=True)
    if result.version != 4:
        raise ValueError("management CIDRs must be IPv4; CubeVS drops native IPv6 before policy")
    if result.prefixlen == 0:
        raise ValueError("management CIDR cannot cover all IPv4 destinations")
    return result


def match(n):
    return f"((ip & 0x{int(n.netmask):08x}U) == 0x{int(n.network_address):08x}U)"


def render(management, resolvers):
    if not management or len(management) > 32:
        raise ValueError("supply 1..32 management CIDRs, including every worker/control-plane public IP")
    protected = [network(x) for x in management]
    dns = [ipaddress.ip_address(x) for x in resolvers]
    if len(dns) > 8 or any(x.version != 4 for x in dns):
        raise ValueError("supply at most 8 exact IPv4 DNS resolver addresses")
    if any(address in cidr for address in dns for cidr in protected):
        raise ValueError("a management address cannot be exempted as a DNS resolver")
    fixed = [ipaddress.ip_network(x) for x in MANDATORY]
    conditions = " ||\n        ".join(match(n) for n in fixed + protected)
    resolver_conditions = " || ".join(f"bpf_ntohl(address) == 0x{int(x):08x}U" for x in dns) or "false"
    return f'''/* Generated by Baarcha render_hard_deny.py. Operator-owned worker policy.
 * Management: {", ".join(str(x) for x in protected)}
 * Resolver exceptions (UDP/53 only): {", ".join(str(x) for x in dns) or "none"}
 * Do not include this header in tenant images or accept it from an API request.
 */
#ifndef BAARCHA_HARD_DENY_H
#define BAARCHA_HARD_DENY_H
#include <bpf/bpf_endian.h>
static __always_inline bool baarcha_hard_deny_ip(__u32 address)
{{
    __u32 ip = bpf_ntohl(address);
    return {conditions};
}}
static __always_inline bool baarcha_hard_deny_flow(__u32 address, __u16 port, __u8 protocol)
{{
    /* DNS is the sole private-address exception: UDP to exact trusted
     * resolvers on port 53. Management addresses cannot be resolver exceptions.
     * Existing Cube DNS query filtering still decides which names are allowed.
     */
    if (protocol == 17 && port == bpf_htons(53) && ({resolver_conditions}))
        return false;
    return baarcha_hard_deny_ip(address);
}}
#endif
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--management-cidr", action="append", required=True)
    parser.add_argument("--dns-resolver", action="append", default=[])
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        output = render(args.management_cidr, args.dns_resolver)
    except ValueError as error:
        parser.error(str(error))
    args.output.write_text(output)


if __name__ == "__main__":
    main()
