#!/usr/bin/env node
// Operator fixture only: source generated by make-canary.py, no customer data.
import fs from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
import { publishEncrypted, fetchEncrypted } from './source-store.mjs';
const directory = process.argv[2];
if (!directory || process.argv.length !== 3) throw Error('one fixture directory required');
const require = createRequire('/opt/baarcha/app/landing/package.json');
const sdk = require('@aws-sdk/client-s3');
const region = process.env.PUNICAS_REGION || 'eu-central-1';
const config = { version: 1, project_id: 'operator-canary-20260927', revision_id: 'source-v1', bucket: process.env.PUNICAS_BUCKET || 'punicas', prefix: 'baarcha/cube/private-source-canary' };
const client = new sdk.S3Client({ region, endpoint: `https://s3.${region}.amazonaws.com`, maxAttempts: 1 });
const keyFile = '/var/lib/sandboxd/secrets.key';
const keyStat = await fs.stat(keyFile);
if (keyStat.uid !== 0 || (keyStat.mode & 0o077) !== 0) throw Error('private existing encryption key required');
const master = Buffer.from((await fs.readFile(keyFile, 'utf8')).trim(), 'base64');
try {
  const source = await fs.readFile(path.join(directory, 'source.zip'));
  const manifest = JSON.parse(await fs.readFile(path.join(directory, 'manifest.json'), 'utf8'));
  const started = performance.now();
  const send = (name, input) => client.send(new sdk[name + 'Command'](input));
  const receipt = await publishEncrypted(config, source, manifest, send, master);
  const fetched = await fetchEncrypted(config, receipt, send, master);
  if (!fetched.source.equals(source)) throw Error('canary source mismatch');
  await fs.writeFile(path.join(directory, 's3-receipt.json'), JSON.stringify({ ...receipt, elapsed_ms: Math.round(performance.now() - started) }, null, 2), { flag: 'wx', mode: 0o600 });
  console.log(JSON.stringify({ verified: true, source_bytes: source.length, excluded_paths: manifest.excluded.length, elapsed_ms: Math.round(performance.now() - started), deployment_ready: false }));
} catch (error) {
  console.error(JSON.stringify({ verified: false, error_name: error.name, status: error.$metadata?.httpStatusCode ?? null }));
  process.exitCode = 1;
} finally { master.fill(0); client.destroy(); }
