import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {APP,SANDBOX,WORKER,OperatorFixture,candidateManifest,patchServer,patchHTML,confirmEffective,digest} from './fixture.mjs';
import {HOME_FILE,HARD,LINK,SCRIPT,names,createHomeFixture,readRecoveryProof} from './home-worker.mjs';
const run='0123456789abcdef';
const manifest='web:\n  command: node server.mjs\n  port: 3000\nworkers:\n  - name: postgres\n    command: node /opt/services/postgres/start.mjs\n    restart_after_task: false\nbuild:\n  command: pnpm install --offline\n';
const source="import express from 'express';\nconst app = express();\napp.listen(3000);\n";
const html='<html><body>notes</body></html>';
function fixture(){
 const files=new Map([['sandbox.yaml',Buffer.from(manifest)],['server.mjs',Buffer.from(source)],['public/index.html',Buffer.from(html)]]),tasks=Array.from({length:4},(_,i)=>({id:String(i),status:'failed',checkpoint_id:'kept-'+i})),original=Buffer.from('{"pending":"original failed AI task"}');
 const c={run,app_id:APP,sandbox_id:SANDBOX,task_inventory_sha256:digest(JSON.stringify(tasks)),original_journal_sha256:digest(original),before_sha256:Object.fromEntries([...files].map(([k,v])=>[k,digest(v)]))};
 const j={},artifacts=new Map(),writes=[],rows=[];let reloads=0;
 const proof={run,hardlink_same_inode:true,uid:1000,file_mode:0o640,script_mode:0o750};
 const io={guard:async()=>{},tasks:async()=>structuredClone(tasks),originalJournal:async()=>original,save:async()=>{},artifact:async(k,v)=>{assert(!artifacts.has(k));artifacts.set(k,Buffer.from(v));},events:async id=>Buffer.from('failed-event-'+id),read:async k=>files.get(k)||null,write:async(k,v)=>{writes.push(k);files.set(k,Buffer.from(v));},validate:async raw=>({valid:true,effective:{web:{command:'node server.mjs',port:3000},workers:[{name:'postgres',command:'original'},...(raw.includes(WORKER)?[{name:WORKER,command:'operator'}]:[])]}}),checkSyntax:async()=>{},workerSource:async()=>Buffer.from('// reviewed helper'),reload:async()=>{reloads++},waitProof:async()=>structuredClone(proof),health:async()=>({status:'ok'}),html:async()=>files.get('public/index.html').toString(),notes:async()=>structuredClone(rows),insertNote:async body=>{const row={id:'1',body,created_at:'2026-09-25T00:00:00Z'};rows.push(row);return row;},privateCapture:async()=>({owner_read:true,foreign_denied:true,anonymous_denied:true})};
 return{f:new OperatorFixture(c,j,io),c,j,io,files,tasks,original,artifacts,writes,rows,reloads:()=>reloads};
}
test('manifest addition preserves all original bytes and flags',()=>{const out=candidateManifest(manifest,run);assert.equal(out.replace(`  - name: ${WORKER}\n    command: node .operator-recovery/${run}/home-worker.mjs ${run}\n    restart_after_task: false\n`,''),manifest);assert(out.indexOf(WORKER)<out.indexOf('build:'));});
test('reject overlapping workers, flow YAML, ambiguous source anchors',()=>{for(const raw of [manifest+WORKER,manifest+'operator_frontend_profile',manifest.replace('workers:','workers: []'),manifest+'workers:\n'])assert.throws(()=>candidateManifest(raw,run));assert.throws(()=>patchServer(source+source,run));assert.throws(()=>patchHTML(html+html,run));});
test('effective comparison refuses hidden unrelated web and worker changes',()=>{const base={valid:true,effective:{web:{port:3000},workers:[{name:'postgres',command:'original'}]}};const next=structuredClone(base);next.effective.workers.push({name:WORKER});confirmEffective(base,next);next.effective.web.port=3001;assert.throws(()=>confirmEffective(base,next));});
test('full protocol preserves original AI failure history, restores manifest, distinguishes source proof',async()=>{const x=fixture();await x.f.prepare();await x.f.install();await x.f.restoreManifest();await x.f.verify();assert.equal(x.files.get('sandbox.yaml').toString(),manifest);assert.equal(x.reloads(),2);assert.deepEqual(x.artifacts.get('original-ai-journal.json'),x.original);assert.equal([...x.artifacts.keys()].filter(k=>k.endsWith('.events')).length,4);assert(x.tasks.every(t=>t.status==='failed'&&t.checkpoint_id));assert.equal(x.rows.length,1);assert.equal(x.j.verified.ai_coding_passed,false);assert.equal(x.j.verified.backup,false);assert.equal(x.j.verified.restore,false);assert.equal(x.j.pending,undefined);});
test('source/hash or original journal drift refuses before any mutation',async()=>{for(const kind of ['source','journal','task']){const x=fixture();if(kind==='source')x.files.set('server.mjs',Buffer.from('new source'));if(kind==='journal')x.io.originalJournal=async()=>Buffer.from('changed');if(kind==='task')x.tasks[0].status='running';await assert.rejects(x.f.prepare());assert.equal(x.writes.length,0);}});
test('syntax check failure prevents all guest writes',async()=>{const x=fixture();x.io.checkSyntax=async()=>{throw Error('invalid syntax')};await assert.rejects(x.f.prepare());assert.equal(x.writes.length,0);assert(!x.j.prepared);});
test('ambiguous file acknowledgement persists intent and refuses repeated mutation',async()=>{const x=fixture();await x.f.prepare();const write=x.io.write;x.io.write=async(...a)=>{await write(...a);throw Error('response lost')};await assert.rejects(x.f.install());assert.equal(x.writes.length,1);assert(x.j.pending.name.startsWith('write:'));await assert.rejects(x.f.install());assert.equal(x.writes.length,1);});
test('task starting between writes prevents subsequent replacements',async()=>{const x=fixture();await x.f.prepare();const write=x.io.write;x.io.write=async(...a)=>{await write(...a);x.tasks[0].status='running'};await assert.rejects(x.f.install());assert.equal(x.writes.length,1);assert.equal(x.files.get('server.mjs').toString(),source);});
test('ambiguous reload does not claim installed or retry',async()=>{const x=fixture();await x.f.prepare();x.io.reload=async()=>{throw Error('lost')};await assert.rejects(x.f.install());assert.equal(x.j.pending.name,'install-reload');assert(!x.j.installed);const count=x.writes.length;await assert.rejects(x.f.install());assert.equal(x.writes.length,count);});
test('manifest drift blocks restoring an obsolete manifest',async()=>{const x=fixture();await x.f.prepare();await x.f.install();x.files.set('sandbox.yaml',Buffer.from('new operator manifest'));const count=x.writes.length;await assert.rejects(x.f.restoreManifest());assert.equal(x.writes.length,count);});
test('lost SQL acknowledgement is retained and cannot duplicate an acknowledged row',async()=>{const x=fixture();await x.f.prepare();await x.f.install();await x.f.restoreManifest();const insert=x.io.insertNote;x.io.insertNote=async b=>{await insert(b);throw Error('response lost')};await assert.rejects(x.f.verify());assert.equal(x.j.pending.name,'sql-row');await assert.rejects(x.f.verify());assert.equal(x.rows.length,1);});
test('capture ACL failure cannot claim completion',async()=>{const x=fixture();await x.f.prepare();await x.f.install();await x.f.restoreManifest();x.io.privateCapture=async()=>({owner_read:true,foreign_denied:false,anonymous_denied:true});await assert.rejects(x.f.verify());assert(!x.j.verified);assert.equal(x.j.pending.name,'private-capture');});
test('complete readback limit refuses before mutation',async()=>{const x=fixture();await assert.rejects(x.f.put('large',Buffer.alloc(2*1024*1024+1),null));assert.equal(x.writes.length,0);});
function diskFixture(t){const tmp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'operator-fixture-')));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));const app=path.join(tmp,'workspace','app');fs.mkdirSync(path.join(app,'.operator-recovery',run),{recursive:true});fs.writeFileSync(names(run,app,tmp).app,`operator-recovery-${run}:app`);fs.chmodSync(names(run,app,tmp).app,0o644);return{tmp,app,home:names(run,app,tmp).home,uid:process.getuid()};}
test('actual filesystem proof preserves special names, relative symlink, hardlink and exact modes',t=>{const x=diskFixture(t);const proof=createHomeFixture(run,x.app,x.tmp,x.uid);assert.equal(proof.home_file,HOME_FILE);assert.equal(proof.hardlink_count,2);assert.deepEqual(createHomeFixture(run,x.app,x.tmp,x.uid),proof);assert.equal(fs.statSync(path.join(x.home,SCRIPT)).mode&0o777,0o750);});
test('partial existing home fails closed without repair',t=>{const x=diskFixture(t);fs.mkdirSync(x.home);fs.writeFileSync(path.join(x.home,HOME_FILE),'retained partial');assert.throws(()=>createHomeFixture(run,x.app,x.tmp,x.uid));assert.equal(fs.readFileSync(path.join(x.home,HOME_FILE),'utf8'),'retained partial');});
for(const kind of ['content','mode','link','hardlink'])test(`actual proof refuses changed ${kind}`,t=>{const x=diskFixture(t);createHomeFixture(run,x.app,x.tmp,x.uid);if(kind==='content')fs.writeFileSync(path.join(x.home,HOME_FILE),'changed');if(kind==='mode')fs.chmodSync(path.join(x.home,SCRIPT),0o777);if(kind==='link'){fs.unlinkSync(path.join(x.home,LINK));fs.symlinkSync('/etc/passwd',path.join(x.home,LINK));}if(kind==='hardlink'){fs.unlinkSync(path.join(x.home,HARD));fs.copyFileSync(path.join(x.home,HOME_FILE),path.join(x.home,HARD));}assert.throws(()=>readRecoveryProof(run,x.app,x.tmp,x.uid));});
